% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  10pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{setspace}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
  \setmainfont[]{Times New Roman}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{greek}
\ifPDFTeX
\else
\babelfont[greek]{rm}{Times New Roman}
\fi
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{array}
\usepackage{longtable}
\usepackage{graphicx}
\usepackage{float}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdflang={el},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\begin{titlepage}
  \centering
  \vspace*{2cm}
  
  {\Huge\bfseries Ανάλυση Δεδομένων\par}
  \vspace{1.5cm}
  

  {\Large Aleksandra Petukhova\par}
  \vspace{1cm}
 
  {\Large 3210229\par}
  \vspace{0.5cm}

  \vfill
\end{titlepage}

\setstretch{1.5}
\section*{Εισαγωγή – Περιγραφή Μελέτης και Προβλήματος}

Σκοπός της μελέτης είναι η διερεύνηση των χαρακτηριστικών ενός ακινήτου
που επηρεάζουν την τιμή πώλησής του και η πρόβλεψη της αναμενόμενης
αξίας μεταπώλησης ενός σπιτιού με βάση τα συγκεκριμένα χαρακτηριστικά.

Για την εξαγωγή της μελέτης επιλέχθηκε σετ δεδομένων που αποτελείται από
τυχαίο δείγμα 117 σπιτιών στην πόλη του Albuquerque, στο Νέο Μεξικό των
ΗΠΑ. Τα στοιχεία καταγράφηκαν στο διάστημα μεταξύ 15 Φεβρουαρίου και 30
Απριλίου του 1993. Το σετ περιλαμβάνει πληροφορίες για την τιμή πώλησης
του ακινήτου, την ετήσια φορολόγηση του, καθώς και διάφορα άλλα
χαρακτηριστικά σπιτιών που καταγράφηκαν.

\begin{longtable}[t]{llll}
\caption{\label{tab:unnamed-chunk-1}Πίνακας Δεδομένων}\\
\toprule
\textbf{Όνομα} & \textbf{Τύπος Μεταβλητής} & \textbf{Σημασία} & \textbf{Τιμές}\\
\midrule
price & αριθμητική & Αξία πώλησης (χιλιάδες δολάρια) & \\
sqft & αριθμητική & Εσωτερικό μέγεθος σπιτιού (τετραγωνικά πόδια) & \\
age & αριθμητική & Ηλικία σπιτιού (έτη) & \\
feats & αριθμητική & Αριθμός χαρακτηριστικών (π.χ. πλυντήριο, ψυγείο κλπ.) & 0 – 11\\
ne & κατηγορική & Το σπίτι βρίσκεται στην ΒΑ πλευρά της πόλης & 0: όχι, 1: ναι\\
\addlinespace
cor & κατηγορική & Το σπίτι είναι γωνιακό & 0: όχι, 1: ναι\\
resale & κατηγορική & Έχει πουληθεί ξανά στο παρελθόν & 0: όχι, 1: ναι\\
tax & αριθμητική & Ετήσιος φόρος (δολάρια) & \\
\bottomrule
\end{longtable}

\section*{Περιγραφική Ανάλυση}

Για να εξετάσουμε τα βασικά χαρακτηριστικά των ποσοτικών μεταβλητών που
περιλαμβάνονται στο σύνολο δεδομένων μας, ξεκινάμε με μία περιγραφική
ανάλυση. Χρησιμοποιούμε στατιστικά μέτρα όπως η μέση τιμή, η διάμεσος, η
τυπική απόκλιση και η ασυμμετρία για να αποκτήσουμε μία πρώτη εικόνα για
την κατανομή των τιμών. Παρακάτω παρουσιάζονται τέσσερις μεταβλητές:
PRICE, SQFT, AGE και TAX, όπως φαίνονται και στον Πίνακα 2.

Ξεκινώντας με τη μεταβλητή PRICE, η οποία αντιπροσωπεύει την τιμή των
ακινήτων, βλέπουμε ότι υπάρχουν συνολικά 117 παρατηρήσεις και δεν
υπάρχουν καθόλου απούσες τιμές. Η μέση τιμή είναι 1062.74, ενώ η
διάμεσος είναι μικρότερη (960), κάτι που μας δείχνει ότι υπάρχουν
μερικές υψηλότερες τιμές που τραβούν τη μέση τιμή προς τα πάνω. Αυτό
επιβεβαιώνεται και από τη θετική τιμή της ασυμμετρίας (1.38), η οποία
υποδηλώνει δεξιά κατανομή. Το εύρος τιμών είναι μεγάλο (540 έως 2150),
ενώ και το ενδοτεταρτημοριακό εύρος είναι 420, δείχνοντας σημαντική
διασπορά στις τιμές.

Η μεταβλητή SQFT, που αναφέρεται στα τετραγωνικά μέτρα των ακινήτων,
επίσης περιλαμβάνει 117 παρατηρήσεις χωρίς απουσίες. Η μέση τιμή είναι
1653.85 και η διάμεσος είναι 1549, επομένως και εδώ υπάρχει μια ελαφρά
δεξιά ασυμμετρία (skew = 1.19). Οι τιμές κυμαίνονται από 837 έως 3750,
με IQR ίσο με 614, δείχνοντας και πάλι ότι υπάρχει σημαντική
μεταβλητότητα στο μέγεθος των ακινήτων.

Στην περίπτωση της AGE, που αφορά την ηλικία των ακινήτων, παρατηρούμε
ότι υπάρχουν αρκετές απούσες τιμές (περίπου 42\% των παρατηρήσεων
λείπουν). Από τις τιμές που διαθέτουμε, η μέση ηλικία είναι 14.97 έτη
και η διάμεσος είναι ελαφρώς μικρότερη (13 έτη), ενώ και εδώ εντοπίζεται
δεξιά ασυμμετρία (1.27). Το εύρος ηλικιών είναι από 1 έως 53 έτη, με IQR
ίσο με 13.5.

Τέλος, η μεταβλητή TAX, η οποία αναφέρεται στον φόρο ακινήτου, έχει 107
παρατηρήσεις, με ένα ποσοστό απουσιών περίπου 8.5\%. Η μέση τιμή είναι
793.49, ενώ η διάμεσος είναι λίγο μικρότερη (731), δείχνοντας και εδώ
ήπια δεξιά ασυμμετρία (skew = 1.06). Το εύρος τιμών είναι από 223 έως
1765 και το IQR είναι 319, που δείχνει επίσης αρκετή διακύμανση.

Παρατηρούμε λοιπόν ότι και οι τέσσερις ποσοτικές μεταβλητές παρουσιάζουν
δεξιά ασυμμετρία,αυτό τονίζεται και διαγραμματικά βλ. σχήμα 1, κάτι που
σημαίνει ότι υπάρχουν υψηλές τιμές που επηρεάζουν τη μορφή της
κατανομής. Αν και δεν μπορούμε να πούμε με βεβαιότητα ότι οι κατανομές
τους αποκλίνουν έντονα από την κανονική, η παρουσία ασυμμετρίας αποτελεί
ένδειξη ότι ίσως χρειάζεται μετασχηματισμός των δεδομένων σε επόμενα
στάδια της ανάλυσης.

Η περιγραφική ανάλυση των κατηγορικών μεταβλητών δείχνει πως οι
μεταβλητές AREA, COR και RESALE δεν έχουν ομοιόμορφη κατανομη. Η
μεταβλητή \textbf{FEATS} (αριθμός παροχών ή χαρακτηριστικών) εμφανίζει
κατανομή τύπου καμπάνας, με τη συχνότερη τιμή να είναι τα
\textbf{4 χαρακτηριστικά}, ενώ οι περισσότερες κατοικίες διαθέτουν από 3
έως 5. Τιμές μικρότερες του 2 και μεγαλύτερες του 6 εμφανίζονται σπάνια,
κάτι που υποδεικνύει συμμετρική κατανομή γύρω από τη μέση τιμή. Η
μεταβλητή \textbf{AREA}, η οποία πιθανώς υποδεικνύει κατηγορία ζώνης,
παρουσιάζει \textbf{ασύμμετρη κατανομή}, καθώς η πλειοψηφία των
παρατηρήσεων ανήκει στην κατηγορία 1. Η μεταβλητή \textbf{COR}, που
πιθανότατα σχετίζεται με γωνιακότητα οικοπέδου, δείχνει ότι περίπου τα
δύο τρίτα των κατοικιών \textbf{δεν είναι γωνιακά} (COR = 0), ενώ το
υπόλοιπο ένα τρίτο αφορά γωνιακά ακίνητα. Παρομοίως, η μεταβλητή
\textbf{RESALE}, που δηλώνει αν ένα ακίνητο αποτελεί μεταπώληση ή όχι,
καταγράφει σαφή υπεροχή της τιμής 0, δηλαδή
\textbf{πρωτογενείς πωλήσεις}, έναντι των μεταπωλήσεων. Συνολικά, οι
μεταβλητές \textbf{AREA}, \textbf{COR} και \textbf{RESALE} είναι
ανισοκατανεμημένες, γεγονός που θα πρέπει να ληφθεί υπόψη στην επόμενη
φάση του υποδείγματος, καθώς η μειωμένη ποικιλία κατηγοριών ενδέχεται να
επηρεάσει τη στατιστική ισχύ. Από την άλλη, η μεταβλητή \textbf{FEATS}
εμφανίζει ισορροπημένη κατανομή και πιθανόν να συμβάλει σημαντικά στην
ερμηνεία της τιμής του ακινήτου (\texttt{PRICE}).

Η περιγραφική ανάλυση των κατηγορικών μεταβλητών δείχνει πως οι
μεταβλητές \textbf{AREA}, \textbf{COR} και RESALE δεν έχουν ομοιόμορφη
κατανομη με κάποιες κατηγορίες να κυριαρχούν. Αυτό μπορεί να έχει
επίπτωση στη στατιστική ισχύ κατά την ενταξή τους σε μοντέλο πρόβλεψης.
Αντίθετα, η μεταβλητή \textbf{FEATS} παρουσιάζει αρκετά κανονική
κατανομή και θα μπορούσε να έχει σημαντική ερμηνευτική αξία, εφόσον
εξεταστεί στατιστικά με την τιμή,για λεπτομέρειες βλ. σχήμα 2 στο
Παράρτημα.

\begin{table}

\caption{\label{tab:desc}Πίνακας περιγραφικών μέτρων ποσοτικών μεταβλητών}
\centering
\begin{tabular}[t]{llrrrrrrrlrr}
\toprule
Μεταβλητή & label & n & NA.prc & mean & sd & se & md & trimmed & range & iqr & skew\\
\midrule
2 & PRICE & 117 & 0.00 & 1062.74 & 380.44 & 35.17 & 960 & 1003.94 & 1610 (540-2150) & 420.0 & 1.38\\
3 & SQFT & 117 & 0.00 & 1653.85 & 523.72 & 48.42 & 1549 & 1594.33 & 2913 (837-3750) & 614.0 & 1.19\\
1 & AGE & 68 & 41.88 & 14.97 & 12.67 & 1.54 & 13 & 13.14 & 52 (1-53) & 13.5 & 1.27\\
4 & TAX & 107 & 8.55 & 793.49 & 308.18 & 29.79 & 731 & 764.48 & 1542 (223-1765) & 319.0 & 1.06\\
\bottomrule
\end{tabular}
\end{table}

Οι πληροφορίες αυτές είναι χρήσιμες προκειμένου να αποφασίσουμε ποιοι
στατιστικοι ελεγχοι είναι κατάλληλοι για τις συγκεκριμένες μεταβλητές.
Στην μεταβλητή AGE συγκεντρώσαμε έναν μεγάλο αριθμό άγνωστων/ελλιπών
τιμών βλ. πίνακα 5. Θα εξετάσουμε όλο το σετ δεδομένων για παρουσία
τέτοιων τιμών.

Στον παρακάτω πίνακα (βλ. πίνακας 3) παρατηρούμε ότι υπάρχουν ελλιπείς
τιμές σε δύο μεταβλητές: στην AGE και στην TAX.Το ποσοστό αυτών
αντιστοιχεί στο 41.9\% των παρατηρήσεων και 8.55\% αντίστοιχα.

Η ύπαρξη τόσο μεγάλου ποσοστού ελλιπών τιμών στη μεταβλητή AGE αποτελεί
πρόβλημα για την ανάλυση. Αν διατηρήσουμε αυτή τη μεταβλητή και
επιλέξουμε να αναλύσουμε μόνο τις παρατηρήσεις όπου υπάρχουν διαθέσιμες
τιμές για όλες τις μεταβλητές (μέθοδος listwise deletion), τότε
αυτομάτως χάνουμε σχεδόν τις μισές παρατηρήσεις. Αυτό μπορεί να μειώσει
τη στατιστική ισχύ της ανάλυσής μας, καθώς και να δημιουργήσει σφάλμα
στα αποτελέσματα, εάν οι τιμές που λείπουν δεν είναι τυχαίες (δηλαδή αν
υπάρχει κάποιο μοτίβο).

Από την άλλη πλευρά, αν επιλέξουμε να εξαιρέσουμε εντελώς τη μεταβλητή
AGE από το μοντέλο μας, τότε μπορούμε να διατηρήσουμε περισσότερες
παρατηρήσεις. Αυτό είναι μπορεί να είναι θετικό διότι ενδεχομένως να
οδηγήσει σε στατιστικά πιο σταθερά αποτελέσματα, ειδικά αν η μεταβλητή
AGE δεν έχει ισχυρή συσχέτιση με τη μεταβλητή εξόδου του μοντέλου.
Ωστόσο, υπάρχει και το ενδεχόμενο να χάσουμε πολύτιμη πληροφορία, αν η
ηλικία του ακινήτου είναι ένας σημαντικός προβλεπτικός παράγοντας.

Για να αποφασίσουμε αν η εξαίρεση της μεταβλητής AGE αλλάζει τα
αποτελέσματα, μπορούμε να εκτελέσουμε την ανάλυσή μας δύο φορές: μία
φορά με όλες τις μεταβλητές (και άρα με λιγότερες παρατηρήσεις) και μία
χωρίς την μεταβλητή AGE (αλλά με περισσότερες παρατηρήσεις). Αν
διαπιστώσουμε ότι τα αποτελέσματα δεν αλλάζουν σημαντικά, τότε ίσως να
είναι προτιμότερο να την αφαιρέσουμε. Αν όμως υπάρχουν ουσιαστικές
διαφοροποιήσεις, θα πρέπει να εξετάσουμε μεθόδους αντιμετώπισης των
ελλιπών τιμών, όπως η πολλαπλή συμπλήρωση (multiple imputation).

Θα προβούμε στην μελέτη των ακραίων τιμών, διαγραμματικά και για
καλύτερη κατανόηση οι τιμές αναδυκνύονται συνοπτικά στον παραπάνω πίνακα
(βλ. πίνακα 3).

Οι ακραίες τιμές μπορούν να είναι λάθη καταγραφής και σε αυτή την
περίπτωση τα διορθώνουμε ή τα αφαιρούμε. Αν είναι σπάνιες αλλά
πραγματικές τιμές, κρίνουμε ανάλογα με τον σκοπό της ανάλυσης. Αν
επηρεάζουν σημαντικά τα αποτελέσματα ή «τραβούν» το μοντέλο προς μη
ρεαλιστικές προβλέψεις, μπορεί να είναι απαραίτητο να τις εξαιρέσουμε.

Εντοπίζοντας τις μεταβλητές που περιέχουν ακραίες τιμές και εξετάζοντάς
τες σε σχέση με το συνολικό εύρος των τιμών, διαπιστώνουμε ότι όλες
εμπίπτουν σε ρεαλιστικά πλαίσια. Για παράδειγμα, στη μεταβλητή PRICE,
τιμές που προσεγγίζουν τα 2 εκατομμύρια θεωρούνται εύλογες στην
πραγματική αγορά. Αντίστοιχα, και οι υπόλοιπες ποσοτικές μεταβλητές
παρουσιάζουν τιμές που κρίνονται αποδεκτές. Συνεπώς, δεν κρίνεται
απαραίτητο να εξαιρέσουμε τις ακραίες τιμές.

\begin{table}

\caption{\label{tab:outliers}Πίνακας ακραίων τιμών}
\centering
\begin{tabular}[t]{l|l|l|l}
\hline
PRICE & SQFT & AGE & TAX\\
\hline
2050 & 2921 & 53 & 1639\\
\hline
2080 & 2931 & 41 & 1635\\
\hline
2150 & 2848 & 46 & 1732\\
\hline
2150 & 3750 & 43 & 1534\\
\hline
1999 &  & 40 & 1765\\
\hline
1900 &  & 40 & 1487\\
\hline
2150 &  & 45 & \\
\hline
2100 &  &  & \\
\hline
1844 &  &  & \\
\hline
\end{tabular}
\end{table}

\section*{Σχέσεις ανά δύο}

Κυριότερος στόχος είναι να διαπισώσουμε ποιοι παράγοντες επηρεάζουν την
τελική τιμή πώλησης ακινήτων στην αγορά, προκειμένου να μπορέσουμε να
προβλέψουμε τυχόν τιμές γνωρίζοντας κοποια χαρακτηριστικά σπιτιού. Για
να επιτευχθεί ο στόχος αυτός θέτουμε ερωτήματα όπως; Η περιοχή προβλέπει
την τιμή; Συσχετίζεται ο φόρος με την τιμή;Τα παλαιότερα σπίτια
κοστίζουν λιγότερο; Από τα ερωτήματα που αφορούν την τιμή προκύπτουν οι
παρακάτω σχέσεις, που πρέπει να μελετηθουν, δηλαδή πρέπει να εκτιμηθεί
αν υπάρχει σχέση μεταξύ της ποσοτικής μεταβλητής-τιμής και κάθε άλλης
τιμής παρούσας στο σετ δεδομένων.Παράλληλα όμως, θα εξεταστούν και τυχόν
σχέσεις μεταξύ ποιοτικών μεταβλητών.Επιπλέον με βάση των , θα αναλυθεί
πώς επηρεάζεται ο φόρος από το μέγεθος ακινήτου.

\section*{{\large Σχέσεις προς μελέτη}}

\begin{itemize}
  \item Τιμή -- Τοποθεσία
  \item Τιμή -- Εσωτερικό μέγεθος σπιτιού
  \item Τιμή -- Χαρακτηριστικά
  \item Τιμή -- Φόρος
  \item Τιμή -- Ηλικία ακινήτου
  \item Τιμή -- Πώληση στο παρελθόν
  \item Φόρος -- Εσωτερικό μέγεθος σπιτιού
\end{itemize}

Σε κάθε ζεύγος μεταβλητών, εφαρμόστηκαν κατάλληλα tests συνοδευόμενα από
διαγράμματα για οπτικοποίηση σχέσεων. Αναλυτικότερα, για να
διαπιστώσουμε καλύτερα τις σχέσεις ποσοτικών μεταβλητών, χρησιμοποιήθηκε
pearson correlation test. Το αποτέλεσμα έδειξε ότι η τιμή \textbf{PRICE}
συσχετίζεται θετικά με το εσωτερικό μέγεθος σπιτιού \textbf{SQFT} και
επίσης έχει ισχυρή θετική συσχετίση με τον ετήσιο φόρο \textbf{TAX}, για
λεπτομέρειες συχέτισης βλ. σχήμα 5 στο Παράρτημα.

Για την σχέση τιμής και χαρακτηριστικών χρησιμοποιήθηκε Kruskal Wallis
test, διότι η μεταβλητή χαρακτηριστικά είναι πολυ επίπεδη, και ό έλεγχος
συνοδεύεται από ραβδογράμματα. για λεπτομέρειες βλ. σχήμα 6 στο
Παράρτημα.Παρατηρούμε ότι απορρίπτεται η μηδενική υπόθεση(p p-value =
0.001757\textless{} 0.05) αυτό υποδηλώνει ότι τα χαρακτηριστικά ακινήτων
σχετίζονται με διαφορές στην τιμή.

Για την σχέση τιμής και τοποθεσίας, χρησιμοποιήθηκε Wilcoxon εφόσον η
μεταβλητή τοποθεσία αποτελεί μια δίτιμη μεταβλητή και η προϋποθεση
κανονικότητας απορρίπτεται και για τις 2 τιμές 0 και 1(p-value =
0.0001416 και p-value = 5.789e-07). Το αποτέλεσμα δείχνει την απουσία
καποιας σχέσης μεταξύ των συγκεκριμένων μεταβλητών,για λεπτομέρειες
συχέτισης βλ. σχήμα 4 στο Παράρτημα.

Για την σχέση τιμής και γεγονότος πώλησης στο παρελθόν, επαναλήφθηκε η
ίδια διαδικασία και το αποτέλεσμα του Wilcoxon ( p-value = 0.8044)
έδειξε ότι δεν υπάρχει κάποια σχέση μεταξύ τιμής και του γεγονότος ότι
πουλήθηκε/ δεν πουλήθηκε το ακίνητο στο παρελθόν, για λεπτομέρειες
συχέτισης βλ. σχήμα 8 στο Παράρτημα.

΄Εχοντας κάνει τους απαραίτητους ελέγχους εμηνεύσει και τα αντίστοιχα
διαγράμματα καταλήγουμε ότι οι σημαντικόερες σχέσεις που ενδέχεται να
μοντελοποιούν την τιμή και μπορούν να μελετηθούν περεταίρω είναι:

\begin{itemize}
  \item Τιμή -- Εσωτερικό μέγεθος σπιτιού
  \item Τιμή -- Χαρακτηριστικά
  \item Τιμή -- Φόρος
\end{itemize}

\begin{longtable}[]{@{}llll@{}}
\caption{Pearson correlation matrix with p-values}\tabularnewline
\toprule\noalign{}
& PRICE & SQFT & TAX \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& PRICE & SQFT & TAX \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
PRICE & & & \\
SQFT & 0.845 (\textless{} .001) & & \\
TAX & 0.876 (\textless{} .001) & 0.859 (\textless{} .001) & \\
\end{longtable}

Όσον αφορά την μεταβλητή TAX (ετήσιος φόρος) παρουσιάζει ισχυρή γραμμική
συσχέτιση τόσο με την τιμή αγοράς της κατοικίας (PRICE) όσο και με το
εμβαδόν του ακινήτου (SQFT). Όπως φάνηκε στα αντίστοιχα διαγράμματα (για
λεπτομέρειες συσχέτισης βλ. πίνακες Α4 και Α5 στο Παράρτημα), η αύξηση
της τιμής συνδέεται με αντίστοιχη αύξηση του ετήσιου φόρου, γεγονός που
υποδηλώνει ότι ο φόρος αντανακλά τη συνολική αξία της ακίνητης
περιουσίας. Παράλληλα, διαπιστώνεται ότι και το εμβαδόν του ακινήτου
επηρεάζει θετικά τον φόρο, γεγονός αναμενόμενο, καθώς μεγαλύτερα ακίνητα
τείνουν να έχουν υψηλότερη αγοραία αξία και, συνεπώς, μεγαλύτερη
φορολογική επιβάρυνση.Τα αποτελέσματα αυτά καθιστούν τη μεταβλητή TAX
ιδιαίτερα χρήσιμη στην πρόβλεψη ή την κατηγοριοποίηση ακινήτων με βάση
χαρακτηριστικά που σχετίζονται με την αγορά,

\section*{Προβλεπτικά ή Ερμηνευτικά μοντέλα}

Οι ανωτέρω έλεγχοι μας καθοδήγησαν στην επιλογή των μεταβλητών που
επηρεάζουν καθοριστικά την τιμή ενός ακινήτου. Στη συνέχεια, προχωρούμε
στην κατασκευή στατιστικού μοντέλου πρόβλεψης της αξίας μεταπώλησης
κατοικιών, το οποίο θα βασιστεί στις πλέον σημαντικές μεταβλητές. Σκοπός
είναι η ακριβής αποτύπωση της αξίας μέσω του μοντέλου. Ωστόσο, σε πρώτη
φάση, κατασκευάζουμε το μοντέλο έτσι ώστε να περιέχει όλες τις
μεταβλητές και βλέπουμε αν τηρούνται οι υποθέσεις για την εκτέλεση
πολλαπλής παλινδρόμησης.

Για την προϋποθεση κανονικότητας χρησιμοποιήθηκε ο έλεγχος κανονικότητας
Shapiro--Wilk (W = 0.966, p = 0.065) δεν έδειξε στατιστικά σημαντική
απόκλιση από την κανονικότητα. Συνεπώς, τα κατάλοιπα του μοντέλου
κατανέμονται περίπου κανονικά.

Το διάγραμμα καταλοίπων έναντι των προσαρμοσμένων τιμών δεν παρουσίασε
μοτίβο μεταβαλλόμενης διασποράς, κάτι που υποστηρίζει την παραδοχή της
ομοσκεδαστικότητας (ίσης διασποράς σφαλμάτων),για λεπτομέρειες βλ. σχήμα
10 στο Παράρτημα.

Ωστόσο, η εφαρμογή στατιστικού έλεγχου Levene Το αποτέλεσμα του ελέγχου
έδειξε ότι τα κατάλοιπα δεν εμφανίζουν σταθερή διασπορά, γεγονός που
αποτελεί ένδειξη ετεροσκοεδαστικότητας (F = 6.0347, p =
0.001129),απορρίπτεται η μηδενικής υπόθεσης,άρα τα κατάλοιπα δεν
εμφανίζουν σταθερή διασπορά.Η παρουσία ετεροσκεδαστικότητας μπορεί να
οδηγήσει σε αναξιόπιστες εκτιμήσεις.

Για την αντιμετώπιση του ζητήματος, εφαρμόστηκε λογαριθμικός
μετασχηματισμός στην εξαρτημένη μεταβλητή \texttt{PRICE}, με σκοπό τη
σταθεροποίηση της διασποράς και την ενίσχυση της κανονικότητας των
καταλοίπων.

Το νέο μοντέλο εκτιμήθηκε με τη μορφή:

\[
\log(\texttt{PRICE}) \sim \texttt{SQFT} + \texttt{FEATS} + \texttt{AREA} + \texttt{AGE} + \texttt{TAX} + \texttt{COR} + \texttt{RESALE}
\]

Μετά τον μετασχηματισμό, ο έλεγχος Levene επαναλήφθηκε(F = 2.0173, p =
0.1207), γεγονός που δηλώνει ότι δεν υπάρχει στατιστικά σημαντική
διαφορά στις διασπορές των καταλοίπων μεταξύ των ομάδων. Συνεπώς, η
υπόθεση ομοιοσκεδαστικότητας \textbf{δεν απορρίπτεται} και η υπόθεση
ισότητας διασποράς μπορεί πλέον να θεωρηθεί ικανοποιημένη.

Ακολουθεί ο έλεγχος ανεξαρτησίας κατάλοιπων Durbin--Watson (D--W = 1.93
με p = 0.52) Συνεπώς, δεν υπάρχει στατιστικά σημαντική αυτοσυσχέτιση των
σφαλμάτων, και η υπόθεση της ανεξαρτησίας ικανοποιείται.

Αφού επιβεβαιώθηκε η εγκυρότητα του μοντέλου ως προς τις βασικές
υποθέσεις της γραμμικής παλινδρόμησης (Κανονικότητα, Ομοσκεδαστικότητα,
Ανεξαρτησία) προχωρούμε στην επόμενη φάση του εντοπισμού των
σημαντικότερων μεταβλητών που επηρεάζουν την τιμή μεταπώλησης, και τη
δημιουργία ενός ισχυρού και απλού μοντέλου παλινδρόμησης.

Αρχικά θα επαληθεύσουμε το γεγονός ότι οι μεταβλητές Χαρακτηριστικά,
Φόρος και Εσωτερικό μέγεθος σπιτιού όντως μπορούν να αποτελέσουν το
μοντέλο πολλαπλής παλινδρόμησης.Ο έλεγχος θα επιτευχθεί με σταδιακή
προσθήκη των τριών μεταβλητών. και ταυτόχρονα μελετηθεί η συμπεριφορά
του μοντέλου ως προς τις διαθέσιμες μεταβλητές.

Παρατηρούμε ότι το μοντέλο εξηγεί το 86,2\% της διακύμανσης στις τιμές
μεταπώλησης.

Ο συντελεστής της μεταβλητής \texttt{TAX} βρέθηκε στατιστικώς σημαντικός
(\(\beta = 3.91 \times 10^{-4}\), \(p = 0.000372\)), υποδεικνύοντας ότι
η φορολογία σχετίζεται θετικά και σημαντικά με τη λογαριθμισμένη τιμή
του ακινήτου. Επιπλέον, η ανάλυση διακύμανσης τύπου ΙΙ επιβεβαίωσε τη
σημαντική συμβολή της \texttt{TAX} στο υπόδειγμα (\(F = 14.17\),
\(p = 0.00037\)). Ως αρχικό βήμα, εκτιμήθηκε γραμμικό μοντέλο με
λογαριθμισμένη εξαρτημένη μεταβλητή \texttt{log(PRICE)} και
την\texttt{SQFT}.Διαπιστώθηκε ότι η μεταβλητή \textbf{SQFT} (τετραγωνικά
μέτρα) είναι στατιστικά σημαντική (\(p < 2 \times 10^{-16}\)) και εξηγεί
περίπου το 80\% της διακύμανσης στην τιμή (\(R^2 = 0.8045\)). Με την
προσθήκη της μεταβλητής \textbf{FEATS}, το \(R^2\) αυξήθηκε ελάχιστα
(\(R^2 = 0.8065\)), επίσης η ίδια η μεταβλητή δεν είναι στατιστικά
σημαντική (\(p = 0.425\)),το τεστ ANOVA τύπου II το επιβεβαίωσε
(\(F(1, 63) = 261.93\) με \(p < 2 \times 10^{-16}\)). Αντιθέτως, στο
τρίτο μοντέλο, η προσθήκη της μεταβλητής \textbf{TAX} οδήγησε σε αισθητή
βελτίωση(\(R^2 = 00.8425\)), ενώ η \textbf{TAX} παρουσίασε στατιστική
σημαντικότητα (\(p = 0.000372\)), με από ANOVA τύπου II (\(F = 14.17\),
\(p = 0.00037\)). Η \textbf{FEATS} παρέμεινε μη σημαντική και σε αυτό το
μοντέλο. Συνεπώς, καταλήγουμε στο συμπέρασμα ότι οι μεταβλητές
\textbf{SQFT} και \textbf{TAX} αποτελούν τους καταλληλότερους
προβλεπτικούς παράγοντες για την τιμή ακινήτου, βάσει της υψηλής
προσαρμοστικής ικανότητας του μοντέλου και της στατιστικής
σημαντικότητας που επιβεβαιώνεται τόσο από τα αποτελέσματα των
συντελεστών όσο και από την ανάλυση διακύμανσης.

Προσθήκη της μεταβλητής AGE στο μοντέλο

Συνεχίζοντας την διαδικασία πρόσθεσης μεταβλητών, εξετάζουμε την
επίδραση μεταβλητής \textbf{AGE} στο προηγούμενο μοντέλο.Δεν φαίνεται
στατιστικά σημαντική, συγκεκριμένα(\(p = 0.2939\)).Παρουσιάζει επίσης
μια ελάχιστη αύξηση (\(R^2 = 0.843\)).Επομένως δεν μπορούμε να
συμπεριλάβουμε την συγκεκριμένη μεταβλητή, δεν ενισχύει ουσιαστικά το
προβλεπτικό μοντέλο, γεγονός που αποδεικνύεται και από ANOVA τύπου II.

Προσθήκη της μεταβλητής AREA στο μοντέλο

Προσθέτουμε τη μεταβλητή \textbf{AREA} στο υπάρχον μοντέλο. Η μεταβλητή
αυτή δεν αναδεικνύεται στατιστικά σημαντική, καθώς η τιμή-\(p\) είναι
αρκετά υψηλή (\(p = 0.7567\)). Η προσθήκη της συνοδεύεται από μια
αμελητέα αύξηση του συντελεστή προσδιορισμού (\(R^2 = 0.8446\)).Συνεπώς,
η μεταβλητή \textbf{AREA} δεν ενισχύει ουσιαστικά το προβλεπτικό
μοντέλο, όπως επιβεβαιώνεται και από τα αποτελέσματα της ανάλυσης
διασποράς τύπου II (ANOVA).

Προσθήκη της μεταβλητής COR στο μοντέλο

Στο επόμενο στάδιο της ανάλυσης προστίθεται η μεταβλητή \textbf{COR} στο
υπάρχον μοντέλο. Η προσθήκη της \textbf{COR} οδήγησε σεμικρή αλλά
αξιοσημείωτη αύξηση στον συντελεστή προσδιορισμού (\(R^2 = 0.859\)).Η
\textbf{COR} είναι στατιστικά σημαντική (\(p = 0.0173\)).Συμπεράνουμε
ότι η \textbf{COR} συνεισφέρει στη βελτίωση του μοντέλου πρόβλεψης, κάτι
που επιβεβαιώνεται και από τα αποτελέσματα της ανάλυσης διασποράς τύπου
II (ANOVA), όπου παρατηρείται επίσης στατιστικά σημαντική επίδραση
(\(p = 0.0173\)).

Προσθήκη της μεταβλητής RESALE στο τελικό μοντέλο\}

Στο τελικό στάδιο της ανάλυσης εξετάστηκε η μεταβλητή \textbf{RESALE}, η
οποία προστέθηκε στο ήδη εκτεταμένο μοντέλο με τις μεταβλητές
\textbf{SQFT}, \textbf{TAX}, \textbf{AGE}, \textbf{AREA}, \textbf{COR}
και \textbf{FEATS}. Η μεταβλητή αυτή δεν παρουσιάζει στατιστική
σημαντικότητα, καθώς η τιμή-\(p\) είναι \(0.1812\), δηλαδή αρκετά
υψηλότερη από το αποδεκτό όριο σημαντικότητας. Η προσθήκη της οδηγεί σε
οριακή αύξηση στον συντελεστή προσδιορισμού (\(R^2 = 0.8633\)), η οποία
δεν είναι αρκετή ώστε να δικαιολογήσει τη διατήρησή της στο
μοντέλο.Συνεπώς, η μεταβλητή αυτή δεν ενισχύει το προβλεπτικό μοντέλο.

Η τελική μορφή του μοντέλου περιλαμβάνει τις μεταβλητές \textbf{SQFT}
(τετραγωνικά μέτρα), \textbf{TAX} (φόρος) και \textbf{COR} (ένδειξη
γωνιακού οικοπέδου), καθώς αποδείχθηκαν στατιστικά σημαντικές για την
πρόβλεψη της τιμής του ακινήτου (\textit{PRICE}). Το τελικό μοντέλο
εμφανίζει υψηλή προσαρμοστικότητα, με προσαρμοσμένο συντελεστή
προσδιορισμού \(R^2_{\text{adj}} = 0.8483\), γεγονός που σημαίνει ότι
εξηγεί το 84.8\% της διακύμανσης στο μοντέλο.Όλοι οι συντελεστές είναι
στατιστικά σημαντικοί.

\subsection*{Εξίσωση Τελικού Μοντέλου}

\begin{equation}
\log(\text{PRICE}) = 6.124 + 0.0003011 \cdot \text{SQFT} + 0.0003852 \cdot \text{TAX} + 0.1030 \cdot \text{COR}
\end{equation}

\section*{Συμπεράσματα και συζήτηση}

Καταλήξαμε στην ανάπτυξη ενός ικανοποιητικού μοντέλου και σημαντικό
είναι το γεγονός ότι έχει ισχυρή προβλεπτική ικανότητα.Ιδιαίτερα
σημαντικό είναι ότι το μοντέλο διατηρεί απλότητα, κάνοντας χρήση μόλις
τριών από τις έξι διαθέσιμων μεταβλητών, γεγονός που το καθιστά εύχρηστο
και ερμηνεύσιμο. Υπάρχει περιθώριο περαιτέρω διερεύνησης και
βελτιστοποίησης. Μελλοντικές επεκτάσεις θα μπορούσαν να εξετάσουν την
ενσωμάτωση πρόσθετων μεταβλητών, τη χρήση μη γραμμικών μοντέλων ή
τεχνικών μηχανικής μάθησης, προκειμένου να ενισχυθεί η ακρίβεια και η
γενικευσιμότητα του μοντέλου σε ευρύτερα δείγματα δεδομένων.

\section*{Ευρετήριο Πινάκων και διαγραμμάτων}

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{Data-Analysis-Report-Home-prices_files/figure-latex/histograms-1} 

}

\caption{Ιστογράμματα Ποσοτικών Μεταβλητών}\label{fig:histograms}
\end{figure}

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{Data-Analysis-Report-Home-prices_files/figure-latex/categorical bar charts-1} 

}

\caption{Bar chart ποιοτικών μεταβλητών}\label{fig:categorical bar charts}
\end{figure}

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{Data-Analysis-Report-Home-prices_files/figure-latex/age-barplot-1} 

}

\caption{Διάγραμμα Κατηγορίας Ηλικίας}\label{fig:age-barplot}
\end{figure}

\begin{figure}
\centering
\includegraphics{Data-Analysis-Report-Home-prices_files/figure-latex/price-location-1.pdf}
\caption{Boxplot τιμή - τοποθεσία}
\end{figure}

\begin{figure}
\centering
\includegraphics{Data-Analysis-Report-Home-prices_files/figure-latex/price-sqft-1.pdf}
\caption{Scatterplot τιμή - εσωτερικό μέγεθος σπιτιού}
\end{figure}

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{Data-Analysis-Report-Home-prices_files/figure-latex/price-feats-1} 

}

\caption{Σχέση τιμής και αριθμού χαρακτηριστικών}\label{fig:price-feats}
\end{figure}

\begin{figure}
\centering
\includegraphics{Data-Analysis-Report-Home-prices_files/figure-latex/price-tax-1.pdf}
\caption{Scatterplot ττιμή - φόρος}
\end{figure}

\begin{figure}
\centering
\includegraphics{Data-Analysis-Report-Home-prices_files/figure-latex/price-resale -1.pdf}
\caption{Boxplot τιμή - πώληση στο παρελθόν}
\end{figure}

\begin{figure}
\centering
\includegraphics{Data-Analysis-Report-Home-prices_files/figure-latex/residual qq plot -1.pdf}
\caption{Κανονικότητα κατάλοιπων}
\end{figure}

\begin{figure}
\centering
\includegraphics{Data-Analysis-Report-Home-prices_files/figure-latex/residuals homoscedasticity-1.pdf}
\caption{Κατάλοιπα και Προσαρμοσμένες Τιμές}
\end{figure}

\end{document}
